name: Python Quality Checks

on:
  push:
    branches: [ main, dev, stg, prod ]
  pull_request:
    branches: [ main, dev, stg, prod ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff mypy pytest pytest-cov
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      
      - name: Format check with Black
        run: |
          black --check --diff . --line-length 100
      
      - name: Import sort check with isort
        run: |
          isort --check-only --diff . --profile black --line-length 100
      
      - name: Lint with Ruff
        run: |
          ruff check .
      
      - name: Type check with mypy
        run: |
          mypy .